repos:
- repo: local
  hooks:
    - id: black-check
      name: black-check
      entry: black .
      language: system
      types: [ python ]
- repo: local
  hooks:
    - id: isort-check
      name: isort-check
      entry: isort ./src
      language: system
      types: [ python ]
- repo: local
  hooks:
    - id: pylint-check
      name: pylint-check
      entry: pylint
      language: system
      types: [python]
      args: []
