# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: course_category.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'course_category.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ourse_category.proto\x12\x02pb\"\x07\n\x05\x62lank\"9\n\x08\x43\x61tegory\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\":\n\x15\x43reateCategoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\" \n\x12\x43\x61tegoryGetRequest\x12\n\n\x02id\x18\x01 \x01(\t\"0\n\x0c\x43\x61tegoryList\x12 \n\ncategories\x18\x01 \x03(\x0b\x32\x0c.pb.Category2N\n\x0f\x43\x61tegoryService\x12;\n\x0e\x43reateCategory\x12\x19.pb.CreateCategoryRequest\x1a\x0c.pb.Category\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'course_category_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLANK']._serialized_start=29
  _globals['_BLANK']._serialized_end=36
  _globals['_CATEGORY']._serialized_start=38
  _globals['_CATEGORY']._serialized_end=95
  _globals['_CREATECATEGORYREQUEST']._serialized_start=97
  _globals['_CREATECATEGORYREQUEST']._serialized_end=155
  _globals['_CATEGORYGETREQUEST']._serialized_start=157
  _globals['_CATEGORYGETREQUEST']._serialized_end=189
  _globals['_CATEGORYLIST']._serialized_start=191
  _globals['_CATEGORYLIST']._serialized_end=239
  _globals['_CATEGORYSERVICE']._serialized_start=241
  _globals['_CATEGORYSERVICE']._serialized_end=319
# @@protoc_insertion_point(module_scope)
